[Server]
Addr = '0.0.0.0'
Port = 7379
KeepAlive = 300
Timeout = 300
MaxConn = 0
ShardCronFrequency = 1000000000
MultiplexerPollTimeout = 100000000
MaxClients = 200
MaxMemory = 0
EvictionPolicy = 'allkeys-lfu'
EvictionRatio = 0.4
KeysLimit = 20000
AOFFile = './dice-master.aof'
PersistenceEnabled = true
WriteAOFOnCleanup = false
LFULogFactor = 10
LogLevel = 'info'
PrettyPrintLogs = false
EnableMultiThreading = false
StoreMapInitSize = 10240

[Auth]
UserName = 'dice'
Password = ''

[Network]
IOBufferLength = 512
IOBufferLengthMAX = 51200
