services:
  dicedb:
    image: dicedb/dicedb:0.0.2
    platform: linux/amd64
    ports:
      - "7379:7379"

  leaderboard-go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
        - dicedb
    environment:
      - DICEDB_HOST=dicedb
      - DICEDB_PORT=7379
