// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: protos/cmd.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_protos_cmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_protos_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Err   string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Response_VNil
	//	*Response_VInt
	//	*Response_VStr
	//	*Response_VFloat
	//	*Response_VBytes
	Value         isResponse_Value `protobuf_oneof:"value"`
	Attrs         *structpb.Struct `protobuf:"bytes,7,opt,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protos_cmd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cmd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *Response) GetValue() isResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Response) GetVNil() bool {
	if x != nil {
		if x, ok := x.Value.(*Response_VNil); ok {
			return x.VNil
		}
	}
	return false
}

func (x *Response) GetVInt() int64 {
	if x != nil {
		if x, ok := x.Value.(*Response_VInt); ok {
			return x.VInt
		}
	}
	return 0
}

func (x *Response) GetVStr() string {
	if x != nil {
		if x, ok := x.Value.(*Response_VStr); ok {
			return x.VStr
		}
	}
	return ""
}

func (x *Response) GetVFloat() float64 {
	if x != nil {
		if x, ok := x.Value.(*Response_VFloat); ok {
			return x.VFloat
		}
	}
	return 0
}

func (x *Response) GetVBytes() []byte {
	if x != nil {
		if x, ok := x.Value.(*Response_VBytes); ok {
			return x.VBytes
		}
	}
	return nil
}

func (x *Response) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type isResponse_Value interface {
	isResponse_Value()
}

type Response_VNil struct {
	VNil bool `protobuf:"varint,2,opt,name=v_nil,json=vNil,proto3,oneof"`
}

type Response_VInt struct {
	VInt int64 `protobuf:"varint,3,opt,name=v_int,json=vInt,proto3,oneof"`
}

type Response_VStr struct {
	VStr string `protobuf:"bytes,4,opt,name=v_str,json=vStr,proto3,oneof"`
}

type Response_VFloat struct {
	VFloat float64 `protobuf:"fixed64,5,opt,name=v_float,json=vFloat,proto3,oneof"`
}

type Response_VBytes struct {
	VBytes []byte `protobuf:"bytes,6,opt,name=v_bytes,json=vBytes,proto3,oneof"`
}

func (*Response_VNil) isResponse_Value() {}

func (*Response_VInt) isResponse_Value() {}

func (*Response_VStr) isResponse_Value() {}

func (*Response_VFloat) isResponse_Value() {}

func (*Response_VBytes) isResponse_Value() {}

var File_protos_cmd_proto protoreflect.FileDescriptor

var file_protos_cmd_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x77, 0x69, 0x72, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0xcf, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x15, 0x0a, 0x05, 0x76, 0x5f, 0x6e, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x76, 0x4e, 0x69, 0x6c, 0x12, 0x15, 0x0a,
	0x05, 0x76, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x04,
	0x76, 0x49, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x05, 0x76, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x76, 0x53, 0x74, 0x72, 0x12, 0x19, 0x0a, 0x07, 0x76,
	0x5f, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06,
	0x76, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x76, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x76, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x2d, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73,
	0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x77,
	0x69, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_cmd_proto_rawDescOnce sync.Once
	file_protos_cmd_proto_rawDescData []byte
)

func file_protos_cmd_proto_rawDescGZIP() []byte {
	file_protos_cmd_proto_rawDescOnce.Do(func() {
		file_protos_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_cmd_proto_rawDesc), len(file_protos_cmd_proto_rawDesc)))
	})
	return file_protos_cmd_proto_rawDescData
}

var file_protos_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_cmd_proto_goTypes = []any{
	(*Command)(nil),         // 0: wire.Command
	(*Response)(nil),        // 1: wire.Response
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_protos_cmd_proto_depIdxs = []int32{
	2, // 0: wire.Response.attrs:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_cmd_proto_init() }
func file_protos_cmd_proto_init() {
	if File_protos_cmd_proto != nil {
		return
	}
	file_protos_cmd_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_VNil)(nil),
		(*Response_VInt)(nil),
		(*Response_VStr)(nil),
		(*Response_VFloat)(nil),
		(*Response_VBytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_cmd_proto_rawDesc), len(file_protos_cmd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_cmd_proto_goTypes,
		DependencyIndexes: file_protos_cmd_proto_depIdxs,
		MessageInfos:      file_protos_cmd_proto_msgTypes,
	}.Build()
	File_protos_cmd_proto = out.File
	file_protos_cmd_proto_goTypes = nil
	file_protos_cmd_proto_depIdxs = nil
}
